### ISSUE TITLE
Duplicates being inserted by PROCESS-SUGGESTIONS

### ISSUE THREAD

**Issue by fcbr** [arademaker/wordnet-editor#4]
A somewhat serious issue: PROCESS-SUGGESTIONS is inserting duplicates.  Example:

http://wnpt.brlcloud.com:10035/repositories/wn30#node/_:b871D4C92x457562
http://wnpt.brlcloud.com:10035/repositories/wn30#node/_:b871D4C92x460951
http://wnpt.brlcloud.com:10035/repositories/wn30#node/_:b871D4C92x465219

**Comment by fcbr** [comment]
Find out synsets that contain more than one word sense linking to the same word.

``` SPARQL
select *
{
  ?a wn30:containsWordSense ?ws1 .
  ?a wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .
  filter (?ws1 != ?ws2) .
}
```

**Comment by arademaker** [comment]
How many cases?

Alexandre 
Sent from my iPhone

**Comment by arademaker** [comment]
Getting the lexicographical greater uri between ws1 and ws2, we can run a SPARQL DELETE for removing one of the senses.

**Comment by fcbr** [comment]
This issue tracks three things:
1. Delete the extra triples inserted;
2. Investigate other possible problems;
3. Fix the WORDNET-EDITOR code so that this doesn't happen again.

**Comment by fcbr** [comment]
Unfortunately we can't do an unconditional SPARQL DELETE since it could delete a word sense that has other links such as these:

http://wnpt.brlcloud.com:10035/repositories/wn30#node/%3Chttps://w3id.org/own-pt/wn30-pt/instances/wordsense-00929839-v-1%3E

But since all word senses are that are blank nodes don't contain any extra important properties, we might be able to concoct a SPARQL DELETE that eliminates only the duplicate blank node.

``` SPARQL
select distinct ?r
{
  ?ws a wn30:WordSense .
  ?ws ?r ?x .
  filter ( isBlank(?ws) ) .
}
```

**Comment by fcbr** [comment]
``` SPARQL
delete { ?s wn30:containsWordSense ?ws1 . }
where
{
  ?s wn30:containsWordSense ?ws1 .
  ?s wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .
  filter (?ws1 < ?ws2 && isBlank(?ws1)) .
}
```

I think this does the trick, but need to double check.  After running it on a test server, only three duplicates remain, all are non-blank nodes, so those can be easily deleted manually after verification.

EDIT: changed from != to < at @arademaker 's suggestion below.

**Comment by arademaker** [comment]
It is important to replace != with < so you don't have the symmetric closure, each pair will be list only one time.

**Comment by arademaker** [comment]
Instead of indirectly avoid to remove senses with extra information choosing only the ones that are blank nodes, I would prefer to explicit restriction to not selet the ones with income or outcome properties other than the rdf:type, wn30:containsWordsense, rdfs:label and wn30:word.

Two ways to address it:

http://www.w3.org/TR/sparql11-query/#neg-minus
http://www.w3.org/TR/sparql11-query/#func-not-in

**Comment by fcbr** [comment]
Re: https://github.com/own-pt/wordnet-editor/issues/4#issuecomment-176118578 we also need to delete the triples related to the duplicate word senses _themselves_.  That query only deletes the `wn30:containsWordSense` triples.

Here's a tentative version:

``` SPARQL
delete { 
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .
  ?ws1 wn30:word ?w .
  ?s wn30:containsWordSense ?ws1 .
}
where
{
  ?s wn30:containsWordSense ?ws1 .
  ?s wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .
  filter (?ws1 < ?ws2 && isBlank(?ws1)) .
}
```

**Comment by fcbr** [comment]
Re: https://github.com/own-pt/wordnet-editor/issues/4#issuecomment-176225841 looks like this SPARQL does the trick.

``` SPARQL
delete { 
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .
  ?ws1 wn30:word ?w .
  ?a wn30:containsWordSense ?ws1 .
}
where
{
  ?a wn30:containsWordSense ?ws1 .
  ?a wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .  
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .

  filter (?ws1 < ?ws2) .

  filter not exists {
    ?ws1 ?r ?x .
        filter  ( (?r != rdf:type) && (?r != rdfs:label) && (?r != wn30:word) ) .
  }
}
```

EDIT: typo no `delete` (`?s` ao inves de `?a`).

**Comment by arademaker** [comment]
Talvez: 

```
delete { 
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .
  ?ws1 wn30:word ?w .
  ?s wn30:containsWordSense ?ws1 .
}
where
{
  ?a wn30:containsWordSense ?ws1 .
  ?a wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .  
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .

  filter (?ws1 < ?ws2 ) .
  filter not exists {
    ?ws1 ?r ?x .
    filter  ( ?r not in (rdf:type, rdfs:label, wn30:word) ) .
  }
  filter not exists {
    ?y ?r ?ws1  .
     filter  ( ?r not in (wn30:containsWordsense) ) .
  }

}
```

Não sei se precisamos do 

```
?ws1 rdf:type ?t .
?ws1 rdfs:label ?l .
```

no where!

**Comment by fcbr** [comment]
A sua especificao do `where` no ultimo comentario nao retorna nenhuma tripla.

EDIT: nevermind, era um typo (`containsWordsense`).

**Comment by fcbr** [comment]
OK, last try (fixing typos):

``` SPARQL
delete { 
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .
  ?ws1 wn30:word ?w .
  ?a wn30:containsWordSense ?ws1 .
}
where
{
  ?a wn30:containsWordSense ?ws1 .
  ?a wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .  
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .

  filter (?ws1 < ?ws2 ) .
  filter not exists {
    ?ws1 ?r ?x .
    filter  ( ?r not in (rdf:type, rdfs:label, wn30:word) ) .
  }
  filter not exists {
    ?y ?r ?ws1  .
     filter  ( ?r not in (wn30:containsWordSense) ) .
  }
}
```

**Comment by fcbr** [comment]
Nope, still problems.  This query deleted the duplicates **and** the original in at least one case: `<https://w3id.org/own-pt/wn30-pt/instances/synset-01240935-v>`.

**Comment by fcbr** [comment]
The following query explains the problem.  Need to find another way of ordering the word senses.

``` SPARQL
select *
{
  ?a wn30:containsWordSense ?ws1 .
  ?a wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .  
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .

  values ?a { wn30pt:synset-01240935-v } .

  filter (?ws1 < ?ws2 ) .

  filter not exists {
    ?ws1 ?r ?x .
    filter  ( ?r not in (rdf:type, rdfs:label, wn30:word) ) .
  }
  filter not exists {
    ?y ?r ?ws1  .
     filter  ( ?r not in (wn30:containsWordSense) ) .
  }
}
```

**Comment by fcbr** [comment]
OK, maybe this is the **really** final solution.  First we need to rename all blank nodes using `(wordnet::rename-all-blank-wordsenses)` in the file `wordsenses.lisp`.

After removing all the blank nodes, we are finally able to use `<` to properly order them.

Doing this the `DELETE` worked.  Still, with all these problems, much more testing is needed.

**Comment by fcbr** [comment]
We also need to execute the query twice: one with `filter (?ws1 < ?ws2 )` and another `filter (?ws1 > ?ws2 )`.

**Comment by fcbr** [comment]
Part of the bug was found.  If you call `ADD-SYNSET-WORD` in sequence with the same words, it will insert the duplicates.  If you commit the triple store in between invokations, it doesn't.

Looking at some of the suggestions in the SOLR database everything seems to be fine, that is, there aren't any duplicate suggestions there.

So I can only conclude that `PROCESS-SUGGESTIONS` was executed twice during the same Allegro session, generating the duplicates.

All it remains now is to fix `A-S-W`.

**Comment by fcbr** [comment]
https://github.com/own-pt/wordnet-editor/commit/e704c5565804376567ca164c695b2b099353ea01 fixes the code issue.

**Comment by fcbr** [comment]
The triple store was fixed.

**Comment by arademaker** [comment]
Only for the records, VALUE could also be used

https://www.w3.org/TR/sparql11-query/#inline-data

**Comment by arademaker** [comment]
@fcbr realmente não entendi o problema da query:

```
select *
{
  ?a wn30:containsWordSense ?ws1 .
  ?a wn30:containsWordSense ?ws2 .
  ?ws1 wn30:word ?w .
  ?ws2 wn30:word ?w .  
  ?ws1 rdf:type ?t .
  ?ws1 rdfs:label ?l .

  values ?a { wn30pt:synset-01240935-v } .

  filter (?ws1 < ?ws2 ) .

  filter not exists {
    ?ws1 ?r ?x .
    filter  ( ?r not in (rdf:type, rdfs:label, wn30:word) ) .
  }
  filter not exists {
    ?y ?r ?ws1  .
     filter  ( ?r not in (wn30:containsWordSense) ) .
  }
}
```

mesmo as URIs de blank nodes deveria formar uma ordem total.
